spring.application.name=quality-management-system
spring.datasource.url=jdbc:postgresql://localhost:5432/quality_management_db
spring.datasource.username=postgres
spring.datasource.password=0101
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
